In [10]:
import numpy as np
a=np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [4]:
b=np.array([[1,2,3,4,5],[3,66,4,3,2]])
print(b)

[[ 1  2  3  4  5]
 [ 3 66  4  3  2]]


In [7]:
# to get the dimension
print(a.ndim)
print(b.ndim)

1
2


In [8]:
print(a.shape)
print(b.shape)

(3,)
(2, 5)


In [11]:
#to get the datatype
a.dtype



dtype('int16')

In [12]:
#size in bytes
a.itemsize

2

In [13]:
#get total size
a.nbytes

6

In [14]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [19]:
#get a specific value
print(a[1,5])
print(a[1,-2])
#get a specific row
print(a[0, :])
#get a specific column
print(a[:,2])
#getting a little more fancy[start:end:stepsize]
print(a[0, 1:6:2])



13
13
[1 2 3 4 5 6 7]
[ 3 10]
[2 4 6]


In [20]:
a[1,5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [22]:
a[:,2]=5
print(a)
a[:,2]=[1,2]
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [26]:
#3-d example
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)
print(b[0,1,1])
print(b[:,1,:])
b[:,1,:]=[[9,9],[8,8]]
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
4
[[3 4]
 [7 8]]
[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [35]:
#initialsize different types of arrays
#all 0s matrix
a=np.zeros((2,3))
print(a)
a=np.zeros((2,3,3,2))
a=np.ones((4,2,2), dtype='int32')
# print(a)
a=np.full((2,2),99, dtype='float32')
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]
[[99. 99.]
 [99. 99.]]


In [37]:
print(np.full(a.shape,4))
print(np.full_like(a,4))


[[4 4]
 [4 4]]
[[4. 4.]
 [4. 4.]]


In [39]:
#random decimal numbers
print(np.random.rand(4,2))
print(np.random.random_sample(a.shape))

[[0.26695951 0.5111747 ]
 [0.41238734 0.50049184]
 [0.19480156 0.88316081]
 [0.16184445 0.49406602]]
[[0.6633931  0.05151232]
 [0.00641349 0.50859024]]


In [43]:
#random integer values
print(np.random.randint(2,8,size=(4,3)))

[[3 4 4]
 [3 6 7]
 [7 6 2]
 [6 7 6]]


In [44]:
print(np.identity(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [48]:
#repeat an array
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [50]:
output=np.ones((5,5))
print(output)
z=np.zeros((3,3))
z[1,1]=9
print(z)
output[1:-1,1:-1]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [56]:
#be carefull while copying arrays
a=np.array([1,2,3])
# b=a       #in this way b also points to the same array its just an alias
          #to resolve this we can use copy function
# b[0]=100
# print(b)
# print(a)   
b=a.copy()
b[0]=100
print(a)
print(b)


[1 2 3]
[100   2   3]


In [60]:
#mathematics
a=np.array([1,2,3,4])
print(a+2)
print(a-2)
print(a*2)
print(a/2)

print(a)


[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[1 2 3 4]


In [64]:
b=np.array([1,0,1,0])
print(a+b)
print(a**2)
print(np.sin(a))
print(np.cos(a))

[2 2 4 4]
[ 1  4  9 16]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


In [69]:
#Linear Algebra
a=np.ones((2,3))
print(a)
b=np.full((3,2),2)
print(b)

print(np.matmul(a,b))

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]


In [71]:
#find the determinant
c=np.identity(3)
print(np.linalg.det(c))


1.0


In [ ]:
#linear algebra docs
#https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbkgtekRmMWluSVpFa3V4OTduQVhWQ0VaelY1Z3xBQ3Jtc0ttR1pkaVV3WHNkVU1qUXdjdTR3M1RMdl9JQ016cXRHbnVNdVUtWXlxM1A1N3lrakpVZ0lOUnJCWkxqLXBRb3pEa05COTVqVFBWVWcybU9CdUZpNUVmaG9Tb09xbW9QNm9pYkhJUE1zUUg0OVczV2pUQQ&q=https%3A%2F%2Fdocs.scipy.org%2Fdoc%2Fnumpy%2Freference%2Froutines.linalg.html&v=QUT1VHiLmmI

In [76]:
#statistics
stats=np.array([[1,2,3],[4,5,6]])
print(stats)
print(np.min(stats))
print(np.max(stats))
print(np.max(stats, axis=0))
print(np.max(stats, axis=1))

[[1 2 3]
 [4 5 6]]
1
6
[4 5 6]
[3 6]


In [79]:
print(np.sum(stats))
print(np.sum(stats, axis=0))
print(np.sum(stats, axis=1))

21
[5 7 9]
[ 6 15]


In [84]:
#reorganizing arrays
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)
print(before.shape)
after=before.reshape((8,1))
print(after)
after=before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [87]:
#vertically stacking vectors
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])

print(np.vstack([v1,v2]))


[[1 2 3 4]
 [5 6 7 8]]


In [89]:
#horizontal stack
h1=np.ones((2,4))
h2=np.zeros((2,2))
print(np.hstack([h1,h2])) 

[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]


In [94]:
#load data from file without using pandas
filedata=np.genfromtxt('data.txt', delimiter=',')
filedata=filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [ ]:
#miscellaneous
#boolean masking and advanced indexing

In [99]:
#  ****** axis=0 is columns and axis=1 is rows
print(filedata>50)
print(filedata[filedata>50])
#we can index with a list in numpy
print(np.any(filedata>50, axis=0))   # column with value greater than 50
print((filedata>50) &( filedata<100))

[[False False False False  True  True False False False False False False
  False False False False False False]
 [False False False False  True  True False  True False False False False
  False False False False False False]
 [False False False False  True False False False  True False False False
  False False False False  True  True]]
[196  75 766  75  55 999  78  76  88]
[False False False False  True  True False  True  True False False False
 False False False False  True  True]
[[False False False False False  True False False False False False False
  False False False False False False]
 [False False False False False  True False  True False False False False
  False False False False False False]
 [False False False False False False False False  True False False False
  False False False False  True  True]]
